//! **The window thread's waits are one registry, and the code and the document agree with it**
//! (design note 2026-09-26, §9.1's first row and revision (c)8 item 9; budget note R7).
//!
//! `window_waits.tsv` is the registry. Its `# doors` section is held equal to
//! `bt_platform::admission::doors` by reading each type's own constants — through `KEY`, which the
//! `door!` macro builds from the same tokens as the type — never their text. Its `# rows` section
//! *is* `docs/ARCHITECTURE.md` §5.3: the table there is rendered from it, and
//! `scripts/dev/generate-window-waits-table.ps1` writes it back when they differ.
//!
//! A child of `hang_watch` because the stations are `hang_watch`'s: a door's station byte is read
//! back through `Station::from_byte`, which only this module may call.

use std::path::PathBuf;

use bt_platform::admission::{DoorKey, Phase, doors};

use super::{STATION_COUNT, Station};

/// The registry, as the build has it.
const REGISTRY: &str = include_str!("window_waits.tsv");

/// Where the generated table begins and ends in `docs/ARCHITECTURE.md`.
const BEGIN: &str = "<!-- window_waits.tsv: generated by scripts/dev/generate-window-waits-table.ps1; edit the registry, not this table -->\n";
const END: &str = "<!-- window_waits.tsv: end -->";

/// One section's lines, cut at the tabs, after checking its header is `columns`.
fn section(name: &str, columns: &[&str]) -> Vec<Vec<&'static str>> {
    let marker = format!("# {name}");
    let mut lines = REGISTRY
        .lines()
        .skip_while(|line| *line != marker)
        .skip(1)
        .take_while(|line| !line.starts_with("# "))
        .filter(|line| !line.is_empty() && !line.starts_with("##"));
    let header: Vec<&str> = lines
        .next()
        .unwrap_or_else(|| panic!("the registry has a `{marker}` section with a header"))
        .split('\t')
        .collect();
    assert_eq!(header, columns, "`{marker}`'s columns");
    lines
        .map(|line| {
            let cells: Vec<&str> = line.split('\t').collect();
            assert_eq!(cells.len(), columns.len(), "`{marker}`: {line}");
            cells
        })
        .collect()
}

const ROW_COLUMNS: [&str; 5] = ["row", "status", "call", "where", "disposition"];
const DOOR_COLUMNS: [&str; 7] = [
    "door",
    "row",
    "station",
    "phases",
    "call",
    "minted at",
    "measures",
];
const VOCABULARY_COLUMNS: [&str; 3] = ["path", "targets", "reason"];

/// The phases a registry cell names, in the order `Phase` declares them.
fn phases_named(cell: &str) -> Vec<Phase> {
    cell.split(", ")
        .map(|name| match name {
            "Starting" => Phase::Starting,
            "Running" => Phase::Running,
            "Exiting" => Phase::Exiting,
            other => panic!("`{other}` is not a phase"),
        })
        .collect()
}

fn phases_of(key: DoorKey) -> Vec<Phase> {
    [Phase::Starting, Phase::Running, Phase::Exiting]
        .into_iter()
        .filter(|phase| key.phases().contains(*phase))
        .collect()
}

/// RED (A1a, §9.1 row 1) — **every door type is a line of the registry, in its order, and says
/// what its line says: the row, the station and the phases.**
///
/// The registry is the list a reviewer reads and the types are what the compiler holds a door
/// to; a door added, dropped or renumbered on one side only would be a door the budget counts
/// under the wrong row, or a station the hang report prints for the wrong call. The station is
/// compared by the byte the meter enters and read back through `Station::from_byte`, so a byte
/// past the last station — which `from_byte` would quietly answer `starting` for — is red here
/// before any report could print it.
///
/// MUTATION: give `doors::PtyResize` station byte 5 (`Present`) in `bt_platform::admission` and
/// the station assertion goes red; add a door type without a line and the count does.
#[test]
fn every_door_type_is_a_registry_line_and_says_what_the_line_says() {
    let lines = section("doors", &DOOR_COLUMNS);
    let rows: Vec<&str> = section("rows", &ROW_COLUMNS)
        .into_iter()
        .map(|cells| cells[0])
        .collect();
    assert_eq!(
        doors::ALL.len(),
        lines.len(),
        "one door type per registry line"
    );
    for (key, line) in doors::ALL.iter().zip(&lines) {
        let name = key.name();
        assert_eq!(name, line[0], "the registry's order is the types' order");
        assert_eq!(key.row().label(), line[1], "{name}'s row");
        assert!(
            line[1] == "§5.2" || rows.contains(&line[1]),
            "{name} serves row {}, which the rows section does not have",
            line[1]
        );
        let byte = key.station();
        assert!(
            usize::from(byte) < STATION_COUNT,
            "{name}'s station byte {byte} is past the last station"
        );
        let station = Station::from_byte(byte);
        assert_eq!(
            station as u8, byte,
            "{name}'s station byte reads back as itself"
        );
        assert_eq!(format!("{station:?}"), line[2], "{name}'s station");
        assert_eq!(phases_of(*key), phases_named(line[3]), "{name}'s phases");
    }
}

/// RED (A1a) — **the registry's rows are numbered once each and carry a status it knows; its
/// vocabulary names each path once, for the targets there are.**
///
/// A status outside the four is a row whose state nobody can read off; a path listed twice is
/// one effect with two reasons.
///
/// MUTATION: write `status` `closed` on a row and it goes red.
#[test]
fn the_registrys_rows_and_vocabulary_are_well_formed() {
    let rows = section("rows", &ROW_COLUMNS);
    let mut numbers: Vec<&str> = rows.iter().map(|cells| cells[0]).collect();
    for cells in &rows {
        assert!(
            ["done", "open", "ruled to stay", "pending"].contains(&cells[1]),
            "row {} has status `{}`",
            cells[0],
            cells[1]
        );
    }
    let count = numbers.len();
    numbers.sort_unstable();
    numbers.dedup();
    assert_eq!(numbers.len(), count, "a row numbered twice");

    let vocabulary = section("vocabulary", &VOCABULARY_COLUMNS);
    let mut paths: Vec<&str> = vocabulary.iter().map(|cells| cells[0]).collect();
    for cells in &vocabulary {
        for target in cells[1].split(", ") {
            assert!(
                ["all", "windows", "macos"].contains(&target),
                "{} names target `{target}`",
                cells[0]
            );
        }
    }
    let count = paths.len();
    paths.sort_unstable();
    paths.dedup();
    assert_eq!(paths.len(), count, "a vocabulary path listed twice");
}

/// §5.3's table and the doors beneath it, as the registry has them.
fn rendered() -> String {
    let mut table =
        String::from("| # | status | call | where | disposition |\n|---|---|---|---|---|\n");
    for cells in section("rows", &ROW_COLUMNS) {
        table.push_str(&format!("| {} |\n", cells.join(" | ")));
    }
    table.push_str(
        "\n**The doors** — one `bt_platform::admission::doors` type per line of the registry's \
         `# doors` section; the station is the `hang_watch` station its meter enters. No door \
         takes its token until A1d.\n\n",
    );
    table.push_str(
        "| door | row | station | admitted in | call | minted at | measures |\n\
         |---|---|---|---|---|---|---|\n",
    );
    for cells in section("doors", &DOOR_COLUMNS) {
        table.push_str(&format!(
            "| `{}` | {} | `{}` | {} | {} | {} | {} |\n",
            cells[0], cells[1], cells[2], cells[3], cells[4], cells[5], cells[6]
        ));
    }
    table
}

fn repository_root() -> PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .canonicalize()
        .expect("this crate sits two directories below the workspace root")
}

/// RED (A1a, budget note R7) — **`docs/ARCHITECTURE.md` §5.3's table is the registry.**
///
/// The table is rendered from `window_waits.tsv` and compared with the one between the markers;
/// the rendering is left in `target/window-waits-table.md`, which
/// `scripts/dev/generate-window-waits-table.ps1` copies into the document. One list, so the prose
/// and the registry cannot disagree while every check passes.
///
/// MUTATION: edit a status in the registry and not the document (or the reverse) and it goes red.
#[test]
fn the_architecture_table_is_the_registry() {
    let root = repository_root();
    let wanted = rendered();
    let generated = root.join("target").join("window-waits-table.md");
    if let Some(parent) = generated.parent() {
        std::fs::create_dir_all(parent).expect("the workspace has a target directory");
    }
    std::fs::write(&generated, wanted.as_bytes()).expect("target/ is writable");
    let document = std::fs::read_to_string(root.join("docs").join("ARCHITECTURE.md"))
        .expect("docs/ARCHITECTURE.md is checked in")
        .replace("\r\n", "\n");
    let begin = document
        .find(BEGIN)
        .expect("ARCHITECTURE §5.3 has the generated table's opening marker")
        + BEGIN.len();
    let end = begin
        + document[begin..]
            .find(END)
            .expect("and its closing marker, after it");
    let held = &document[begin..end];
    if let Some((number, held_line, wanted_line)) = held
        .lines()
        .map(Some)
        .chain(std::iter::repeat(None))
        .zip(wanted.lines().map(Some).chain(std::iter::repeat(None)))
        .take(held.lines().count().max(wanted.lines().count()))
        .enumerate()
        .find(|(_, (held_line, wanted_line))| held_line != wanted_line)
        .map(|(index, (held_line, wanted_line))| {
            (
                index + 1,
                held_line.unwrap_or("<end of the table>"),
                wanted_line.unwrap_or("<end of the table>"),
            )
        })
    {
        panic!(
            "ARCHITECTURE §5.3's table, line {number}, is not what window_waits.tsv says — \
             run scripts/dev/generate-window-waits-table.ps1\n  \
             the document: {held_line}\n  the registry: {wanted_line}"
        );
    }
    assert_eq!(held, wanted, "the table ends where the registry does");
}
