//! **The lint probe** - generated by `scripts/dev/generate-lint-probe.ps1` from the registry's
//! `# vocabulary` (`crates/bt-app/src/window_waits.tsv`) and `crates/bt-lint-probe/recipes.tsv`;
//! edit those, never this file. One public function per vocabulary entry, each calling its
//! entry on one line that names it, under the `cfg` of the targets the entry is assigned to.
//! Compiled, never run: `cargo clippy -p bt-lint-probe --all-targets -- --force-warn
//! clippy::disallowed_methods` reports the lint once on each line (thread-door note, revisions
//! (j)4 and (j)11.3), and `scripts/ci/check-lint-probe.ps1` requires it.
#![allow(clippy::disallowed_methods)]

/// `std::thread::sleep` - all
pub fn probe_01(d: std::time::Duration) -> impl Sized {
    std::thread::sleep(d) // probe: std::thread::sleep
}

/// `std::thread::JoinHandle::join` - all
pub fn probe_02(h: std::thread::JoinHandle<()>) -> impl Sized {
    h.join() // probe: std::thread::JoinHandle::join
}

/// `std::sync::mpsc::Receiver::recv` - all
pub fn probe_03(r: &std::sync::mpsc::Receiver<()>) -> impl Sized {
    r.recv() // probe: std::sync::mpsc::Receiver::recv
}

/// `std::sync::mpsc::Receiver::recv_timeout` - all
pub fn probe_04(r: &std::sync::mpsc::Receiver<()>, d: std::time::Duration) -> impl Sized {
    r.recv_timeout(d) // probe: std::sync::mpsc::Receiver::recv_timeout
}

/// `std::sync::Condvar::wait` - all
pub fn probe_05<'a>(c: &std::sync::Condvar, g: std::sync::MutexGuard<'a, ()>) -> impl Sized {
    c.wait(g) // probe: std::sync::Condvar::wait
}

/// `std::sync::Condvar::wait_timeout` - all
pub fn probe_06<'a>(
    c: &std::sync::Condvar,
    g: std::sync::MutexGuard<'a, ()>,
    d: std::time::Duration,
) -> impl Sized {
    c.wait_timeout(g, d) // probe: std::sync::Condvar::wait_timeout
}

/// `std::fs::rename` - all
pub fn probe_07(a: &std::path::Path, b: &std::path::Path) -> impl Sized {
    std::fs::rename(a, b) // probe: std::fs::rename
}

/// `std::fs::write` - all
pub fn probe_08(p: &std::path::Path, b: &[u8]) -> impl Sized {
    std::fs::write(p, b) // probe: std::fs::write
}

/// `std::fs::copy` - all
pub fn probe_09(a: &std::path::Path, b: &std::path::Path) -> impl Sized {
    std::fs::copy(a, b) // probe: std::fs::copy
}

/// `std::fs::canonicalize` - all
pub fn probe_10(p: &std::path::Path) -> impl Sized {
    std::fs::canonicalize(p) // probe: std::fs::canonicalize
}

/// `std::fs::metadata` - all
pub fn probe_11(p: &std::path::Path) -> impl Sized {
    std::fs::metadata(p) // probe: std::fs::metadata
}

/// `std::fs::read_dir` - all
pub fn probe_12(p: &std::path::Path) -> impl Sized {
    std::fs::read_dir(p) // probe: std::fs::read_dir
}

/// `std::fs::create_dir_all` - all
pub fn probe_13(p: &std::path::Path) -> impl Sized {
    std::fs::create_dir_all(p) // probe: std::fs::create_dir_all
}

/// `std::fs::File::create` - all
pub fn probe_14(p: &std::path::Path) -> impl Sized {
    std::fs::File::create(p) // probe: std::fs::File::create
}

/// `std::fs::File::sync_data` - all
pub fn probe_15(f: &std::fs::File) -> impl Sized {
    f.sync_data() // probe: std::fs::File::sync_data
}

/// `std::fs::File::sync_all` - all
pub fn probe_16(f: &std::fs::File) -> impl Sized {
    f.sync_all() // probe: std::fs::File::sync_all
}

/// `std::io::Write::write_fmt` - all
pub fn probe_17(w: &mut dyn std::io::Write) -> impl Sized {
    w.write_fmt(format_args!("probe")) // probe: std::io::Write::write_fmt
}

/// `std::process::Command::output` - all
pub fn probe_18(c: &mut std::process::Command) -> impl Sized {
    c.output() // probe: std::process::Command::output
}

/// `std::process::Command::status` - all
pub fn probe_19(c: &mut std::process::Command) -> impl Sized {
    c.status() // probe: std::process::Command::status
}

/// `std::process::Child::wait` - all
pub fn probe_20(c: &mut std::process::Child) -> impl Sized {
    c.wait() // probe: std::process::Child::wait
}

/// `portable_pty::Child::try_wait` - all
pub fn probe_21(c: &mut dyn portable_pty::Child) -> impl Sized {
    c.try_wait() // probe: portable_pty::Child::try_wait
}

/// `pollster::block_on` - all
pub fn probe_22(f: std::future::Ready<()>) -> impl Sized {
    pollster::block_on(f) // probe: pollster::block_on
}

/// `wgpu::Queue::submit` - all
pub fn probe_23(q: &wgpu::Queue, b: wgpu::CommandBuffer) -> impl Sized {
    q.submit([b]) // probe: wgpu::Queue::submit
}

/// `wgpu::Queue::present` - all
pub fn probe_24(q: &wgpu::Queue, t: wgpu::SurfaceTexture) -> impl Sized {
    q.present(t) // probe: wgpu::Queue::present
}

/// `bt_render::GpuContext::open` - all
pub fn probe_25(t: bt_render::WindowTarget) -> impl Sized {
    bt_render::GpuContext::open(t, 1, 1, 1.0) // probe: bt_render::GpuContext::open
}

/// `bt_pty::PtySession::spawn_shell_in` - all
pub fn probe_26(size: bt_pty::PtySize, wake: bt_pty::OutputWake) -> impl Sized {
    bt_pty::PtySession::spawn_shell_in("probe", &[], &[], size, wake, None) // probe: bt_pty::PtySession::spawn_shell_in
}

/// `bt_pty::PtySession::resize` - all
pub fn probe_27(s: &bt_pty::PtySession, size: bt_pty::PtySize) -> impl Sized {
    s.resize(size) // probe: bt_pty::PtySession::resize
}

/// `bt_pty::wait_for_retirements` - all
pub fn probe_28(d: std::time::Duration) -> impl Sized {
    bt_pty::wait_for_retirements(d) // probe: bt_pty::wait_for_retirements
}

/// `windows::Win32::UI::Shell::ShellExecuteW` - windows
#[cfg(windows)]
pub fn probe_29(
    o: windows::core::PCWSTR,
    n: windows::Win32::UI::WindowsAndMessaging::SHOW_WINDOW_CMD,
) -> impl Sized {
    unsafe { windows::Win32::UI::Shell::ShellExecuteW(None, o, o, o, o, n) } // probe: windows::Win32::UI::Shell::ShellExecuteW
}

/// `windows::Win32::System::Threading::SetEvent` - windows
#[cfg(windows)]
pub fn probe_30(h: windows::Win32::Foundation::HANDLE) -> impl Sized {
    unsafe { windows::Win32::System::Threading::SetEvent(h) } // probe: windows::Win32::System::Threading::SetEvent
}

/// `windows::Win32::Foundation::CloseHandle` - windows
#[cfg(windows)]
pub fn probe_31(h: windows::Win32::Foundation::HANDLE) -> impl Sized {
    unsafe { windows::Win32::Foundation::CloseHandle(h) } // probe: windows::Win32::Foundation::CloseHandle
}

/// `libc::write` - macos
#[cfg(target_os = "macos")]
pub fn probe_32(fd: i32, b: &[u8]) -> impl Sized {
    unsafe { libc::write(fd, b.as_ptr().cast(), b.len()) } // probe: libc::write
}

/// `libc::close` - macos
#[cfg(target_os = "macos")]
pub fn probe_33(fd: i32) -> impl Sized {
    unsafe { libc::close(fd) } // probe: libc::close
}
