Section "ServerFlags"
    Option "AutoAddDevices" "false"
    Option "AutoEnableDevices" "false"
    Option "AutoAddGPU" "false"
    Option "DontVTSwitch" "true"
EndSection

Section "InputDevice"
    Identifier "FolioVirtualKeyboard"
    Driver "void"
EndSection

Section "InputDevice"
    Identifier "FolioVirtualPointer"
    Driver "void"
EndSection

Section "Device"
    Identifier "FolioDummy"
    Driver "dummy"
    VideoRam 256000
EndSection

Section "Monitor"
    Identifier "FolioMonitor"
    HorizSync 28-160
    VertRefresh 30-120
    Modeline "1280x800" 83.46 1280 1344 1480 1680 800 801 804 828
EndSection

Section "Screen"
    Identifier "FolioScreen"
    Device "FolioDummy"
    Monitor "FolioMonitor"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "1280x800"
        Virtual 3840 2160
    EndSubSection
EndSection

Section "ServerLayout"
    Identifier "FolioLayout"
    Screen "FolioScreen" 0 0
    InputDevice "FolioVirtualKeyboard" "CoreKeyboard"
    InputDevice "FolioVirtualPointer" "CorePointer"
EndSection
