[package]
name = "bt-app"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
bt-doc = { path = "../bt-doc" }
bt-layout = { path = "../bt-layout" }
bt-math = { path = "../bt-math" }
bt-persist = { path = "../bt-persist" }
bt-platform = { path = "../bt-platform" }
bt-pty = { path = "../bt-pty" }
bt-render = { path = "../bt-render" }
bt-term = { path = "../bt-term" }
bt-transcript = { path = "../bt-transcript" }
bt-viewport = { path = "../bt-viewport" }
pollster.workspace = true
winit.workspace = true

[lints]
workspace = true
