// auto-generated
pub const STRAND: &[(u32, &str, &str)] = &[
    (1, "none", ""),
    (
        2,
        "none",
        "│ Run powershell -ExecutionPolicy Bypass -c '$env:CODEX_NON_INTERACTIVE=1; irm                         │",
    ),
    (
        3,
        "none",
        "│ https://chatgpt.com/codex/install.ps1 | iex' to update.                                              │",
    ),
    (
        4,
        "none",
        "│                                                                                                      │",
    ),
    (
        5,
        "none",
        "│ See full release notes:                                                                              │",
    ),
    (
        6,
        "none",
        "│ https://github.com/openai/codex/releases/latest                                                      │",
    ),
    (
        7,
        "none",
        "╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯",
    ),
    (8, "none", ""),
    (
        9,
        "none",
        "╭──────────────────────────────────────────────────╮",
    ),
    (
        10,
        "none",
        "│ >_ OpenAI Codex (v0.144.4)                       │",
    ),
    (
        11,
        "none",
        "│                                                  │",
    ),
    (
        12,
        "none",
        "│ model:     gpt-5.6-sol medium   /model to change │",
    ),
    (
        13,
        "none",
        "│ directory: D:\\Developer\\folio-terminal\\dist      │",
    ),
    (
        14,
        "none",
        "╰──────────────────────────────────────────────────╯",
    ),
    (15, "none", ""),
    (
        16,
        "none",
        "  Tip: New Use /fast to enable our fastest inference with increased plan usage.",
    ),
    (17, "none", ""),
    (
        18,
        "none",
        "                                                                                                        ",
    ),
    (
        19,
        "none",
        "› 请你输出一些latex公式                                                                                 ",
    ),
    (
        20,
        "none",
        "                                                                                                        ",
    ),
    (21, "none", ""),
    (22, "none", "• 常见的 LaTeX 公式示例："),
    (23, "none", ""),
    (24, "none", "  行内公式：质能方程 (E=mc^2)"),
    (25, "none", ""),
    (26, "none", "  二次公式："),
    (27, "none", "  ["),
    (28, "none", "  x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}"),
    (29, "none", "  ]"),
    (30, "none", ""),
    (31, "none", "  欧拉恒等式："),
    (32, "none", "  ["),
    (33, "none", "  e^{i\\pi}+1=0"),
    (34, "none", "  ]"),
    (35, "none", ""),
    (36, "none", "  定积分："),
    (37, "none", "  ["),
    (38, "none", "  \\int_a^b f(x),\\mathrm{d}x"),
    (39, "none", "  ]"),
    (40, "none", ""),
    (41, "none", "  极限："),
    (42, "none", "  ["),
    (43, "none", "  \\lim_{x\\to 0}\\frac{\\sin x}{x}=1"),
    (44, "none", "  ]"),
    (45, "none", ""),
    (46, "none", "  求和："),
    (47, "none", "  ["),
    (48, "none", "  \\sum_{k=1}^{n}k=\\frac{n(n+1)}{2}"),
    (49, "none", "  ]"),
    (50, "none", ""),
    (51, "none", "  矩阵："),
    (52, "none", "  ["),
    (53, "none", "  a & b\\"),
    (54, "none", "  c & d"),
    (55, "suppressed", "  \\end{pmatrix}"),
    (56, "none", "  ]"),
    (57, "none", ""),
    (58, "none", "  麦克斯韦方程组："),
    (59, "none", "  ["),
    (60, "ready", "  \\begin{aligned}"),
    (
        61,
        "none",
        "  \\nabla\\cdot\\mathbf{E} &= \\frac{\\rho}{\\varepsilon_0},\\",
    ),
    (62, "none", "  \\nabla\\cdot\\mathbf{B} &= 0,\\"),
    (
        63,
        "none",
        "  \\nabla\\times\\mathbf{E} &= -\\frac{\\partial\\mathbf{B}}{\\partial t},\\",
    ),
    (
        64,
        "none",
        "  \\nabla\\times\\mathbf{B} &= \\mu_0\\mathbf{J}",
    ),
    (
        65,
        "none",
        "  +\\mu_0\\varepsilon_0\\frac{\\partial\\mathbf{E}}{\\partial t}.",
    ),
    (66, "none", "  \\end{aligned}"),
    (67, "none", "  ]"),
    (68, "none", ""),
    (
        69,
        "none",
        "                                                                                                        ",
    ),
    (
        70,
        "suppressed",
        "› 请用$$包裹                                                                                            ",
    ),
    (
        71,
        "none",
        "                                                                                                        ",
    ),
    (72, "none", ""),
    (73, "ready", "• $$"),
    (74, "none", "  E=mc^2"),
    (75, "none", "  $$"),
    (76, "none", ""),
    (77, "ready", "  $$"),
    (78, "none", "  x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}"),
    (79, "none", "  $$"),
    (80, "none", ""),
    (81, "ready", "  $$"),
    (82, "none", "  e^{i\\pi}+1=0"),
    (83, "none", "  $$"),
    (84, "none", ""),
    (85, "ready", "  $$"),
    (86, "none", "  \\int_a^b f(x),\\mathrm{d}x"),
    (87, "none", "  $$"),
    (88, "none", ""),
    (89, "ready", "  $$"),
    (90, "none", "  \\lim_{x\\to 0}\\frac{\\sin x}{x}=1"),
    (91, "none", "  $$"),
    (92, "none", ""),
    (93, "ready", "  $$"),
    (94, "none", "  \\sum_{k=1}^{n}k=\\frac{n(n+1)}{2}"),
    (95, "none", "  $$"),
    (96, "none", ""),
    (97, "ready", "  \\begin{pmatrix}"),
    (98, "none", "  a & b\\"),
    (99, "none", "  c & d"),
    (100, "none", "  \\end{pmatrix}"),
    (101, "suppressed", "  $$"),
    (102, "none", ""),
    (103, "suppressed", "  $$"),
    (104, "ready", "  \\begin{aligned}"),
    (
        105,
        "none",
        "  \\nabla\\cdot\\mathbf{E} &= \\frac{\\rho}{\\varepsilon_0},\\",
    ),
    (106, "none", "  \\nabla\\cdot\\mathbf{B} &= 0,\\"),
    (
        107,
        "none",
        "  \\nabla\\times\\mathbf{E} &= -\\frac{\\partial\\mathbf{B}}{\\partial t},\\",
    ),
    (
        108,
        "none",
        "  \\nabla\\times\\mathbf{B} &= \\mu_0\\mathbf{J}",
    ),
    (
        109,
        "none",
        "  +\\mu_0\\varepsilon_0\\frac{\\partial\\mathbf{E}}{\\partial t}.",
    ),
    (110, "none", "  \\end{aligned}"),
    (111, "suppressed", "  $$"),
    (112, "none", ""),
    (
        113,
        "none",
        "                                                                                                        ",
    ),
    (
        114,
        "none",
        "› 请再输出一些                                                                                          ",
    ),
    (
        115,
        "none",
        "                                                                                                        ",
    ),
    (116, "none", ""),
    (117, "ready", "• $$"),
    (118, "none", "  a^2+b^2=c^2"),
    (119, "none", "  $$"),
    (120, "none", ""),
    (121, "ready", "  $$"),
    (
        122,
        "none",
        "  \\frac{\\mathrm{d}}{\\mathrm{d}x}x^n=nx^{n-1}",
    ),
    (123, "none", "  $$"),
    (124, "none", ""),
    (125, "ready", "  $$"),
    (126, "none", "  \\int e^x,\\mathrm{d}x=e^x+C"),
    (127, "none", "  $$"),
    (128, "none", ""),
    (129, "suppressed", "  $$"),
    (
        130,
        "none",
        "  \\int_{-\\infty}^{+\\infty}e^{-x^2},\\mathrm{d}x=\\sqrt{\\pi}",
    ),
    (131, "suppressed", "  $$"),
    (132, "none", ""),
    (133, "ready", "  $$"),
    (
        134,
        "none",
        "  \\lim_{n\\to\\infty}\\left(1+\\frac{1}{n}\\right)^n=e",
    ),
    (135, "none", "  $$"),
    (136, "none", ""),
    (137, "suppressed", "  $$"),
    (
        138,
        "none",
        "  \\sum_{n=1}^{\\infty}\\frac{1}{n^2}=\\frac{\\pi^2}{6}",
    ),
    (139, "suppressed", "  $$"),
    (140, "none", ""),
    (141, "ready", "  $$"),
    (142, "none", "  \\binom{n}{k}=\\frac{n!}{k!(n-k)!}"),
    (143, "none", "  $$"),
    (144, "none", ""),
    (145, "suppressed", "  $$"),
    (146, "none", "  \\sin^2\\theta+\\cos^2\\theta=1"),
    (147, "suppressed", "  $$"),
    (148, "none", ""),
    (149, "suppressed", "  $$"),
    (150, "none", "  e^{ix}=\\cos x+i\\sin x"),
    (151, "suppressed", "  $$"),
    (152, "none", ""),
    (153, "suppressed", "  $$"),
    (154, "none", "  \\frac{\\partial^2u}{\\partial t^2}"),
    (155, "none", "  =c^2\\nabla^2u"),
    (156, "suppressed", "  $$"),
    (157, "none", ""),
    (158, "suppressed", "  $$"),
    (
        159,
        "none",
        "  i\\hbar\\frac{\\partial}{\\partial t}\\Psi(\\mathbf r,t)",
    ),
    (160, "none", ""),
    (161, "none", "  \\hat H\\Psi(\\mathbf r,t)"),
    (162, "suppressed", "  $$"),
    (163, "none", ""),
    (164, "ready", "  $$"),
    (165, "none", "  R_{\\mu\\nu}-\\frac{1}{2}Rg_{\\mu\\nu}"),
    (166, "none", "  +\\Lambda g_{\\mu\\nu}"),
    (167, "none", ""),
    (168, "none", "  \\frac{8\\pi G}{c^4}T_{\\mu\\nu}"),
    (169, "none", "  $$"),
    (170, "none", ""),
    (171, "suppressed", "  $$"),
];
