# Writes the lint probe's two generated files from the registry and the recipes
# (thread-door note 2026-09-26, revisions (j)4 and (j)11.2, (j)11.3, (j)11.8).
#
#   -Source  the probe's one source file (crates/bt-lint-probe/src/lib.rs)
#   -Config  the probe's clippy.toml         (crates/bt-lint-probe/clippy.toml)
#
# It reads two tab-separated files and nothing else: the registry's `# vocabulary`
# (path, targets, reason) and `crates/bt-lint-probe/recipes.tsv` (path, generics,
# params, call). It reads no Rust source: the output paths are parameters, so
# this script names no source file of its own (the tripwire,
# crates/bt-source/tests/tripwire.rs).
#
# One public function per entry, its call on one line that ends by naming the
# entry (`// probe: <path>`), under the `cfg` its targets decide: `all` none,
# `windows` `cfg(windows)`, `macos` `cfg(target_os = "macos")`, both `any(...)`.
# The config lists every entry, so on each target the lint resolves the entries
# that target has and says which it cannot (revision (j)4's target-aware rule).
#
# CI regenerates both files and requires `git diff --exit-code` over them: the
# probe is what the registry says, or the job is red.

param(
    [Parameter(Mandatory = $true)][string]$Source,
    [Parameter(Mandatory = $true)][string]$Config,
    [string]$Registry = "crates/bt-app/src/window_waits.tsv",
    [string]$RecipeTable = "crates/bt-lint-probe/recipes.tsv"
)

$ErrorActionPreference = "Stop"
$repo = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)

function Resolve-Here([string]$path) {
    if ([IO.Path]::IsPathRooted($path)) { return $path }
    return [IO.Path]::GetFullPath((Join-Path $repo $path))
}

# One section of a tab-separated file: the lines after `# name` up to the next section, the
# header line checked, comment lines (`##`) and blank lines skipped.
function Read-Rows([string]$path, [string]$section, [string[]]$columns) {
    $rows = @()
    $inside = $section -eq ""
    $header = $false
    foreach ($line in [IO.File]::ReadAllLines((Resolve-Here $path))) {
        if ($line.StartsWith("##")) { continue }
        if ($section -ne "" -and $line.StartsWith("# ")) { $inside = ($line -eq "# $section"); continue }
        if (-not $inside -or $line.Length -eq 0) { continue }
        $cells = $line -split "`t"
        if (-not $header) {
            if (($cells -join "|") -ne ($columns -join "|")) { throw "${path}: '$section' has columns '$line'" }
            $header = $true
            continue
        }
        if ($cells.Count -ne $columns.Count) { throw "${path}: not $($columns.Count) cells: $line" }
        $row = [ordered]@{}
        for ($i = 0; $i -lt $columns.Count; $i++) { $row[$columns[$i]] = $cells[$i] }
        $rows += [pscustomobject]$row
    }
    if (-not $header) { throw "${path} has no '$section' section with a header" }
    return , $rows
}

$vocabulary = Read-Rows $Registry "vocabulary" @("path", "targets", "reason")
$recipes = Read-Rows $RecipeTable "" @("path", "generics", "params", "call")

$byPath = @{}
foreach ($recipe in $recipes) {
    if ($byPath.ContainsKey($recipe.path)) { throw "recipes.tsv: '$($recipe.path)' twice" }
    $byPath[$recipe.path] = $recipe
}
foreach ($entry in $vocabulary) {
    if (-not $byPath.ContainsKey($entry.path)) { throw "the vocabulary entry '$($entry.path)' has no recipe in $RecipeTable" }
}
foreach ($recipe in $recipes) {
    if (-not ($vocabulary | Where-Object { $_.path -eq $recipe.path })) {
        throw "the recipe '$($recipe.path)' names no vocabulary entry"
    }
}

# `a: X<'a, ()>, b: Y` split at the commas outside brackets.
function Split-TopLevel([string]$text) {
    $parts = @()
    $depth = 0
    $current = ""
    foreach ($char in $text.ToCharArray()) {
        if ("<([".Contains($char)) { $depth++ }
        if (">)]".Contains($char)) { $depth-- }
        if ($char -eq "," -and $depth -eq 0) { $parts += $current.Trim(); $current = ""; continue }
        $current += $char
    }
    if ($current.Trim() -ne "") { $parts += $current.Trim() }
    return , $parts
}

function Cfg-Of([string]$targets) {
    $named = @($targets -split ", " | Where-Object { $_ -ne "" })
    if ($named.Count -eq 0) { throw "an entry assigned to no target" }
    $predicates = @()
    foreach ($target in $named) {
        switch ($target) {
            "all" { return $null }
            "windows" { $predicates += "windows" }
            "macos" { $predicates += 'target_os = "macos"' }
            default { throw "unknown target '$target'" }
        }
    }
    if ($predicates.Count -eq 1) { return "#[cfg($($predicates[0]))]" }
    return "#[cfg(any($($predicates -join ', ')))]"
}

$lines = @(
    "//! **The lint probe** - generated by ``scripts/dev/generate-lint-probe.ps1`` from the registry's",
    "//! ``# vocabulary`` (``crates/bt-app/src/window_waits.tsv``) and ``crates/bt-lint-probe/recipes.tsv``;",
    "//! edit those, never this file. One public function per vocabulary entry, each calling its",
    "//! entry on one line that names it, under the ``cfg`` of the targets the entry is assigned to.",
    "//! Compiled, never run: ``cargo clippy -p bt-lint-probe --all-targets -- --force-warn",
    "//! clippy::disallowed_methods`` reports the lint once on each line (thread-door note, revisions",
    "//! (j)4 and (j)11.3), and ``scripts/ci/check-lint-probe.ps1`` requires it.",
    "#![allow(clippy::disallowed_methods)]"
)
$toml = @(
    "# **The lint probe's vocabulary** - generated by scripts/dev/generate-lint-probe.ps1 from the",
    "# registry's `# vocabulary` (crates/bt-app/src/window_waits.tsv); edit the registry, never this",
    "# file. The fifth file of the configuration fence (thread-door note, revisions (j)3 and (j)11.3):",
    "# it is effective for this probe alone, never for a product crate.",
    "disallowed-methods = ["
)
$index = 0
foreach ($entry in $vocabulary) {
    $index++
    $recipe = $byPath[$entry.path]
    $lines += ""
    $lines += "/// ``$($entry.path)`` - $($entry.targets)"
    $cfg = Cfg-Of $entry.targets
    if ($cfg) { $lines += $cfg }
    $head = "pub fn probe_{0:d2}{1}(" -f $index, $recipe.generics
    $signature = "$head$($recipe.params)) -> impl Sized {"
    if ($signature.Length -le 100) {
        $lines += $signature
    } else {
        # rustfmt's layout for a signature past the width: one parameter a line.
        $lines += $head
        foreach ($param in (Split-TopLevel $recipe.params)) { $lines += "    $param," }
        $lines += ") -> impl Sized {"
    }
    $lines += "    $($recipe.call) // probe: $($entry.path)"
    $lines += "}"
    $reason = $entry.reason.Replace('\', '\\').Replace('"', '\"')
    $toml += "    { path = `"$($entry.path)`", reason = `"$reason`" },"
}
$toml += "]"

$utf8 = New-Object System.Text.UTF8Encoding $false
[IO.File]::WriteAllText((Resolve-Here $Source), (($lines -join "`n") + "`n"), $utf8)
[IO.File]::WriteAllText((Resolve-Here $Config), (($toml -join "`n") + "`n"), $utf8)
Write-Host "the lint probe: $($vocabulary.Count) entries, written to $Source and $Config."
