# Writes `docs/ARCHITECTURE.md` §5.3's table from the registry, `crates/bt-app/src/window_waits.tsv`.
#
# The renderer is not in this file. It is
# `hang_watch::window_waits_tests::the_architecture_table_is_the_registry`, which renders the
# registry's rows and doors, leaves the rendering in `target/window-waits-table.md`, and fails
# when the table between the document's two markers is not that rendering. A second renderer
# written here would be a second opinion about the same table (the pattern of
# `scripts/generate-shortcuts-table.ps1`).
#
# So this script runs that test and puts what it wrote between the markers. The test is the
# gate: CI runs it with the rest of `bt-app`'s tests.

$ErrorActionPreference = "Stop"

# A non-zero exit from cargo is the expected case here - it is what "the table is out of date"
# looks like - so it must not end the script before the copy.
if (Get-Variable -Name PSNativeCommandUseErrorActionPreference -Scope Global -ErrorAction SilentlyContinue) {
    $PSNativeCommandUseErrorActionPreference = $false
}

$repo = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot "..\.."))
$generated = Join-Path $repo "target\window-waits-table.md"
$document = Join-Path $repo "docs\ARCHITECTURE.md"
$begin = "<!-- window_waits.tsv: generated by scripts/dev/generate-window-waits-table.ps1; edit the registry, not this table -->`n"
$end = "<!-- window_waits.tsv: end -->"

if (Test-Path $generated) { Remove-Item $generated -Force }

Push-Location $repo
try {
    & cargo test -p bt-app --locked -j 6 -- --exact `
        hang_watch::window_waits_tests::the_architecture_table_is_the_registry | Out-Host
} finally {
    Pop-Location
}

if (-not (Test-Path $generated)) {
    throw "the renderer never ran: $generated was not written"
}

$utf8 = New-Object System.Text.UTF8Encoding($false)
$table = [IO.File]::ReadAllText($generated, $utf8)
$text = [IO.File]::ReadAllText($document, $utf8).Replace("`r`n", "`n")
$from = $text.IndexOf($begin)
if ($from -lt 0) { throw "docs/ARCHITECTURE.md has no opening marker: $begin" }
$from += $begin.Length
$to = $text.IndexOf($end, $from)
if ($to -lt 0) { throw "docs/ARCHITECTURE.md has no closing marker after the opening one: $end" }
$text = $text.Substring(0, $from) + $table + $text.Substring($to)
[IO.File]::WriteAllText($document, $text, $utf8)
Write-Host "wrote $document"

# The cargo run above is expected to have failed when the table was out of date, and its exit code
# must not become this script's: writing the table is what this script was asked to do.
exit 0
